# Generated by Django 3.2.9 on 2022-09-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('your_info', models.TextField(blank=True)),
                ('location', models.CharField(choices=[('Nairobi City', 'Nairobi City'), ('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Garissa', 'Garissa'), ('wajir', 'wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ("Murang'a", "Murang'a"), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Migori'), ('Nyamira', 'Nyamira')], max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('terms_of_service', models.CharField(choices=[('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Parmanent', 'Parmanent')], max_length=100, null=True)),
                ('date_of_request', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('area_of_specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.areaofspecialization')),
            ],
        ),
        migrations.CreateModel(
            name='jobrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('proposal', models.TextField(blank=True)),
                ('terms_of_service', models.CharField(choices=[('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=100, null=True)),
                ('your_budget', models.FloatField()),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('area_of_specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.areaofspecialization')),
                ('user_requesting', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('job_desc', models.TextField(blank=True)),
                ('budget', models.FloatField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('job_taken', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('area_of_specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.areaofspecialization')),
                ('employer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='HireTalentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('your_specifications', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(choices=[('Nairobi City', 'Nairobi City'), ('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Garissa', 'Garissa'), ('wajir', 'wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ("Murang'a", "Murang'a"), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Migori'), ('Nyamira', 'Nyamira')], max_length=100, null=True)),
                ('terms_of_service', models.CharField(choices=[('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Parmanent', 'Parmanent')], max_length=100, null=True)),
                ('date_of_request', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('area_of_need', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.areaofspecialization')),
            ],
        ),
    ]
